[workspace]
members = ["advent", "leaderboard", "2022/day*", "2023/day*", "2024/day*"]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true


[profile.release-lto-pgo]
inherits = "release"
lto = true
