[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
enum-iterator = "2.1.0"
integer-sqrt = "0.1.5"
num = "0.4.1"
